"""A shared verifier can carry a network policy of its own.

The verifier runs inside the agent's container, so the policy is enforced by
the egress proxy authenticating the two phases as two htpasswd users, each with
its own ACL files. The single-user output is pinned byte-for-byte: a task that
declares no verifier network policy must produce exactly the proxy config and
exec environments pier produced before per-phase policy existed.
"""

import json
import logging
import tempfile
from pathlib import Path
from types import SimpleNamespace

import pytest

from pier.environments.agent_setup import (
    EGRESS_PROXY_SERVICE,
    PROXY_VERIFIER_USER,
    proxy_environment,
    proxy_policy_env,
    squid_bootstrap_command,
    write_docker_proxy_compose,
)
from pier.environments.base import BaseEnvironment
from pier.environments.daytona import DaytonaEnvironment
from pier.environments.docker.docker import DockerEnvironment
from pier.environments.modal import ModalEnvironment
from pier.models.agent.network import NetworkAllowlist
from pier.models.task.config import TaskConfig

from test_trial_verifier_artifact_transfer import (
    _make_env,
    _make_factory_recorder,
    _mock_agent,
    _run_trial,
    run_async,
)

AGENT_ALLOWLIST = NetworkAllowlist(
    domains=["api.example.com"], ip_entries=["10.0.0.0/8"]
)
VERIFIER_ALLOWLIST = NetworkAllowlist(domains=["pypi.org"], ip_entries=["192.0.2.0/24"])

# Generated by pier at commit 9e56148, before per-phase verifier policy existed.
# Any change to this string changes the proxy every existing task runs behind.
HEAD_SINGLE_USER_SCRIPT = r"""#!/usr/bin/env bash
set -eu

printf '%s' "$ALLOWLIST_DOMAINS" | tr ',' '\n' | sed '/^[[:space:]]*$/d' \
  > /tmp/allowed_domains.txt
printf '%s' "$ALLOWLIST_IPS" | tr ',' '\n' | sed '/^[[:space:]]*$/d' \
  > /tmp/allowed_ips.txt

htpasswd -bc /tmp/squid.passwd agent "$PROXY_TOKEN"

cat > /tmp/squid.conf <<'EOF'
http_port 0.0.0.0:8080
pid_filename /tmp/squid.pid
coredump_dir /tmp

auth_param basic program /usr/lib/squid/basic_ncsa_auth /tmp/squid.passwd
auth_param basic realm PierPolicyProxy
acl authenticated proxy_auth REQUIRED

acl SSL_ports port 443
acl Safe_ports port 80 443
acl CONNECT method CONNECT
acl allowed_domains dstdomain "/tmp/allowed_domains.txt"
acl allowed_ips dst "/tmp/allowed_ips.txt"

http_access deny !Safe_ports
http_access deny CONNECT !SSL_ports
http_access allow authenticated allowed_domains
http_access allow authenticated allowed_ips
http_access deny all

cache deny all
access_log stdio:/tmp/squid_access.log
cache_log /tmp/squid_cache.log
log_mime_hdrs off
shutdown_lifetime 1 seconds
EOF

exec squid -N -f /tmp/squid.conf -d 1
"""


def _squid_conf(script: str) -> list[str]:
    """The squid.conf heredoc lines out of a bootstrap script."""
    body = script.split("cat > /tmp/squid.conf <<'EOF'\n", 1)[1]
    return body.split("\nEOF\n", 1)[0].splitlines()


# --------------------------------------------------------------------------
# Backward compatibility: no verifier policy means the single-user output.
# --------------------------------------------------------------------------


@pytest.mark.parametrize(
    "verifier_allowlist", [None, NetworkAllowlist(), NetworkAllowlist(domains=[])]
)
def test_single_user_bootstrap_script_is_byte_identical(verifier_allowlist):
    assert (
        squid_bootstrap_command(AGENT_ALLOWLIST, verifier_allowlist)
        == HEAD_SINGLE_USER_SCRIPT
    )


def test_single_user_proxy_policy_env_carries_no_verifier_keys():
    assert proxy_policy_env(AGENT_ALLOWLIST, "tok") == {
        "PROXY_TOKEN": "tok",
        "ALLOWLIST_DOMAINS": "api.example.com",
        "ALLOWLIST_IPS": "10.0.0.0/8",
    }
    assert proxy_policy_env(AGENT_ALLOWLIST, "tok", NetworkAllowlist(), None) == {
        "PROXY_TOKEN": "tok",
        "ALLOWLIST_DOMAINS": "api.example.com",
        "ALLOWLIST_IPS": "10.0.0.0/8",
    }


def test_single_user_compose_file_is_byte_identical(tmp_path):
    args = {
        "path": tmp_path / "compose.json",
        "proxy_dir": tmp_path / "proxy",
        "allowlist": AGENT_ALLOWLIST,
        "token": "secret",
    }
    without = write_docker_proxy_compose(**args).read_text()
    with_empty = write_docker_proxy_compose(
        **args, verifier_allowlist=NetworkAllowlist(), verifier_token=None
    ).read_text()

    assert without == with_empty
    assert (tmp_path / "proxy" / "start-squid.sh").read_text() == (
        HEAD_SINGLE_USER_SCRIPT
    )
    compose = json.loads(without)
    env = compose["services"][EGRESS_PROXY_SERVICE]["environment"]
    assert not any(key.startswith("VERIFIER_") for key in env)


def test_agent_proxy_url_still_names_the_agent_user():
    assert proxy_environment("secret", "host")["HTTP_PROXY"] == (
        "http://agent:secret@host:8080"
    )


# --------------------------------------------------------------------------
# Two-user proxy.
# --------------------------------------------------------------------------


def test_two_user_script_provisions_a_second_user_and_acl_files():
    script = squid_bootstrap_command(AGENT_ALLOWLIST, VERIFIER_ALLOWLIST)

    assert 'htpasswd -bc /tmp/squid.passwd agent "$PROXY_TOKEN"' in script
    assert 'htpasswd -b /tmp/squid.passwd verifier "$VERIFIER_PROXY_TOKEN"' in script
    assert "/tmp/allowed_domains_verifier.txt" in script
    assert "/tmp/allowed_ips_verifier.txt" in script


def test_two_user_rules_are_scoped_per_proxy_user():
    conf = _squid_conf(squid_bootstrap_command(AGENT_ALLOWLIST, VERIFIER_ALLOWLIST))

    assert "acl agent_user proxy_auth agent" in conf
    assert "acl verifier_user proxy_auth verifier" in conf
    allows = [line for line in conf if line.startswith("http_access allow")]
    assert allows == [
        "http_access allow agent_user allowed_domains",
        "http_access allow agent_user allowed_ips",
        "http_access allow verifier_user allowed_domains_verifier",
        "http_access allow verifier_user allowed_ips_verifier",
    ]


def test_verifier_only_policy_grants_the_agent_nothing():
    """A no-network agent phase around an allowlisted verifier phase."""
    conf = _squid_conf(squid_bootstrap_command(NetworkAllowlist(), VERIFIER_ALLOWLIST))

    allows = [line for line in conf if line.startswith("http_access allow")]
    assert allows == [
        "http_access allow verifier_user allowed_domains_verifier",
        "http_access allow verifier_user allowed_ips_verifier",
    ]
    assert not any("agent_user" in line for line in conf)


def test_two_user_policy_env_carries_both_halves():
    env = proxy_policy_env(
        AGENT_ALLOWLIST, "agent-tok", VERIFIER_ALLOWLIST, "verifier-tok"
    )

    assert env["PROXY_TOKEN"] == "agent-tok"
    assert env["VERIFIER_PROXY_TOKEN"] == "verifier-tok"
    assert env["VERIFIER_ALLOWLIST_DOMAINS"] == "pypi.org"
    assert env["VERIFIER_ALLOWLIST_IPS"] == "192.0.2.0/24"


def test_verifier_proxy_url_names_the_verifier_user():
    assert (
        proxy_environment("secret", "host", user=PROXY_VERIFIER_USER)["HTTP_PROXY"]
        == "http://verifier:secret@host:8080"
    )


# --------------------------------------------------------------------------
# Hardening: nothing but the two phase allowlists is reachable.
# --------------------------------------------------------------------------


@pytest.mark.parametrize("verifier_allowlist", [NetworkAllowlist(), VERIFIER_ALLOWLIST])
def test_squid_config_denies_cache_manager_to_proxy_users(verifier_allowlist):
    conf = _squid_conf(squid_bootstrap_command(AGENT_ALLOWLIST, verifier_allowlist))
    access = [line for line in conf if line.startswith("http_access")]

    # Nothing grants the cache manager, and deny-all is the last word: an allow
    # rule added after it would be unreachable, so squid administration stays
    # closed to every authenticated phase.
    assert not any("manager" in line for line in conf)
    assert access[-1] == "http_access deny all"
    # Every allow names the proxy user it belongs to, so no rule is anonymous.
    assert all(
        line.split()[2] in {"authenticated", "agent_user", "verifier_user"}
        for line in access
        if line.startswith("http_access allow")
    )


# --------------------------------------------------------------------------
# Parse matrix for a shared verifier.
# --------------------------------------------------------------------------


def _shared_task(agent_mode: str, verifier_mode: str) -> str:
    verifier_hosts = (
        'allowed_hosts = ["pypi.org"]' if verifier_mode == "allowlist" else ""
    )
    return f"""
[agent]
network_mode = "{agent_mode}"
[verifier]
network_mode = "{verifier_mode}"
{verifier_hosts}
[environment]
docker_image = "example/image:tag"
"""


RESTRICTED = ["no-network", "allowlist"]


@pytest.mark.parametrize("agent_mode", RESTRICTED + ["public"])
@pytest.mark.parametrize("verifier_mode", RESTRICTED + ["public"])
def test_shared_verifier_parse_matrix(agent_mode: str, verifier_mode: str):
    TaskConfig.model_validate_toml(_shared_task(agent_mode, verifier_mode))


def test_shared_verifier_allowlist_hosts_are_the_verifier_phase_only():
    cfg = TaskConfig.model_validate_toml(_shared_task("no-network", "allowlist"))

    assert cfg.shared_verifier_allowed_hosts() == ["pypi.org"]
    assert cfg.shared_verifier_proxy_hosts() == ["pypi.org"]
    assert cfg.agent_allowed_hosts() == []
    assert cfg.environment.network_mode.value == "public"


def test_no_network_verifier_phase_gets_no_credentials():
    cfg = TaskConfig.model_validate_toml(
        """
[agent]
network_mode = "allowlist"
allowed_hosts = ["api.example.com"]
[verifier]
network_mode = "no-network"
[environment]
docker_image = "example/image:tag"
"""
    )

    assert cfg.shared_verifier_proxy_hosts() == []
    assert cfg.agent_allowed_hosts() == ["api.example.com"]


def test_matching_shared_verifier_uses_the_baseline_allowlist():
    cfg = TaskConfig.model_validate_toml(
        """
[environment]
network_mode = "allowlist"
allowed_hosts = ["api.example.com"]
"""
    )

    assert cfg.shared_verifier_proxy_hosts() == []
    assert cfg.agent_allowed_hosts() == ["api.example.com"]


def test_step_verifier_phase_owns_its_hosts():
    cfg = TaskConfig.model_validate_toml(
        """
[environment]
network_mode = "no-network"
[[steps]]
name = "one"
[steps.verifier]
network_mode = "allowlist"
allowed_hosts = ["crates.io"]
"""
    )

    assert cfg.shared_verifier_allowed_hosts(cfg.steps[0]) == ["crates.io"]
    assert cfg.shared_verifier_proxy_hosts() == ["crates.io"]
    assert cfg.agent_allowed_hosts() == []


def test_multistep_proxy_omits_fully_overridden_task_defaults():
    cfg = TaskConfig.model_validate_toml(
        """
[environment]
network_mode = "no-network"
[agent]
network_mode = "allowlist"
allowed_hosts = ["unused-agent.example"]
[verifier]
network_mode = "allowlist"
allowed_hosts = ["unused-verifier.example"]

[[steps]]
name = "one"
[steps.agent]
network_mode = "allowlist"
allowed_hosts = ["step-agent.example"]
[steps.verifier]
network_mode = "allowlist"
allowed_hosts = ["step-verifier.example"]
"""
    )

    assert cfg.agent_allowed_hosts() == ["step-agent.example"]
    assert cfg.shared_verifier_proxy_hosts() == ["step-verifier.example"]


# --------------------------------------------------------------------------
# Environment wiring.
# --------------------------------------------------------------------------


def _docker_env(tmp_path: Path, allowlist, verifier_allowlist) -> DockerEnvironment:
    env = DockerEnvironment.__new__(DockerEnvironment)
    env.network_allowlist = allowlist
    env.verifier_network_allowlist = verifier_allowlist
    env.task_env_config = type("TaskEnv", (), {"has_public_network": False})()
    env.trial_paths = SimpleNamespace(trial_dir=tmp_path)
    env.environment_dir = tmp_path / "environment"  # Dockerfile task, no compose
    env._egress_proxy_env = {}
    env._verifier_proxy_env = {}
    env._egress_proxy_compose_path = None
    return env


def test_docker_provisions_two_users_only_with_a_verifier_policy(tmp_path):
    env = _docker_env(tmp_path, AGENT_ALLOWLIST, VERIFIER_ALLOWLIST)

    env._prepare_egress_proxy_compose()

    agent_env = env.agent_process_env(None)
    verifier_env = env.verifier_process_env(None)
    assert agent_env["HTTP_PROXY"].startswith("http://agent:")
    assert verifier_env["HTTP_PROXY"].startswith("http://verifier:")
    assert agent_env["HTTP_PROXY"] != verifier_env["HTTP_PROXY"]
    compose = json.loads(env._egress_proxy_compose_path.read_text())
    proxy = compose["services"][EGRESS_PROXY_SERVICE]["environment"]
    assert proxy["VERIFIER_ALLOWLIST_DOMAINS"] == "pypi.org"
    assert proxy["VERIFIER_PROXY_TOKEN"] != proxy["PROXY_TOKEN"]


def test_docker_without_verifier_policy_has_no_verifier_credentials(tmp_path):
    env = _docker_env(tmp_path, AGENT_ALLOWLIST, NetworkAllowlist())

    env._prepare_egress_proxy_compose()

    assert env.verifier_process_env({"A": "b"}) == {"A": "b"}
    assert (tmp_path / "egress-proxy" / "start-squid.sh").read_text() == (
        HEAD_SINGLE_USER_SCRIPT
    )


def test_docker_starts_the_proxy_for_a_verifier_only_allowlist(tmp_path):
    """agent='no-network' + verifier='allowlist': the proxy exists for one user."""
    env = _docker_env(tmp_path, NetworkAllowlist(), VERIFIER_ALLOWLIST)

    env._prepare_egress_proxy_compose()

    assert env._egress_proxy_compose_path is not None
    assert env.verifier_process_env(None)["HTTP_PROXY"].startswith("http://verifier:")


def test_modal_verifier_process_env_merges_verifier_credentials():
    env = ModalEnvironment.__new__(ModalEnvironment)
    env._egress_proxy_env = proxy_environment("agent-tok", "r123.modal.host", 12345)
    env._verifier_proxy_env = proxy_environment(
        "verifier-tok", "r123.modal.host", 12345, user=PROXY_VERIFIER_USER
    )

    assert env.verifier_process_env({"X": "1"}) == {
        **env._verifier_proxy_env,
        "X": "1",
    }
    assert "verifier-tok" not in json.dumps(env.agent_process_env(None))


def test_environment_without_phase_scoped_egress_rejects_the_policy():
    env = DaytonaEnvironment.__new__(DaytonaEnvironment)
    env._compose_mode = False
    env.agent_install_spec = None
    env.task_env_config = type("TaskEnv", (), {"has_public_network": False})()
    env.network_allowlist = NetworkAllowlist()
    env.verifier_network_allowlist = VERIFIER_ALLOWLIST
    env.logger = logging.getLogger("test")

    assert env.capabilities.phase_scoped_egress is False
    with pytest.raises(ValueError, match="per-phase egress"):
        BaseEnvironment._validate_agent_setup_options(env)


# --------------------------------------------------------------------------
# Trial wiring: the credentials reach the verifier command and nothing else.
# --------------------------------------------------------------------------

SHARED_VERIFIER_POLICY_TOML = """
[agent]
timeout_sec = 10.0
network_mode = "no-network"
[verifier]
timeout_sec = 10.0
network_mode = "allowlist"
allowed_hosts = ["deps.internal.example"]
[environment]
network_mode = "no-network"
"""

SAME_MODE_SHARED_TOML = """
[agent]
timeout_sec = 10.0
[verifier]
timeout_sec = 10.0
[environment]
network_mode = "allowlist"
allowed_hosts = ["deps.internal.example"]
"""

VERIFIER_PROXY_URL = "http://verifier:secret@pier-egress-proxy:8080"
AGENT_PROXY_URL = "http://agent:secret@pier-egress-proxy:8080"


def _task(tmp: Path, toml: str) -> Path:
    task_dir = tmp / "task"
    task_dir.mkdir()
    (task_dir / "task.toml").write_text(toml)
    (task_dir / "instruction.md").write_text("Do nothing.\n")
    env_dir = task_dir / "environment"
    env_dir.mkdir()
    (env_dir / "Dockerfile").write_text("FROM ubuntu:24.04\n")
    tests_dir = task_dir / "tests"
    tests_dir.mkdir()
    (tests_dir / "Dockerfile").write_text("FROM ubuntu:24.04\n")
    (tests_dir / "test.sh").write_text("#!/bin/bash\nexit 0\n")
    return task_dir


async def _run(tmp: Path, toml: str):
    trials_dir = tmp / "trials"
    trials_dir.mkdir()
    agent_env = _make_env(mounted=True)
    agent_env.verifier_process_env.side_effect = lambda process_env: {
        **(process_env or {}),
        "HTTP_PROXY": VERIFIER_PROXY_URL,
    }
    agent_env.agent_process_env.side_effect = lambda process_env: {
        **(process_env or {}),
        "HTTP_PROXY": AGENT_PROXY_URL,
    }
    fake_create, calls = _make_factory_recorder(agent_env, [])
    await _run_trial(
        _task(tmp, toml),
        trials_dir,
        fake_create,
        agent=_mock_agent(NetworkAllowlist(domains=["api.model.example"])),
    )
    return calls, agent_env


@run_async
async def test_shared_verifier_policy_reaches_the_environment_and_the_command():
    with tempfile.TemporaryDirectory() as tmp:
        calls, agent_env = await _run(Path(tmp), SHARED_VERIFIER_POLICY_TOML)

        assert len(calls) == 1  # still one container
        assert calls[0]["verifier_network_allowlist"].domains == [
            "deps.internal.example"
        ]
        # The verifier's host is not in the agent's allowlist.
        assert calls[0]["network_allowlist"].domains == ["api.model.example"]
        exec_envs = [call.kwargs.get("env") for call in agent_env.exec.await_args_list]
        assert any(
            env is not None and env.get("HTTP_PROXY") == VERIFIER_PROXY_URL
            for env in exec_envs
        )
        agent_env.agent_process_env.assert_not_called()


@run_async
async def test_shared_verifier_inherits_baseline_proxy_env():
    with tempfile.TemporaryDirectory() as tmp:
        calls, agent_env = await _run(Path(tmp), SAME_MODE_SHARED_TOML)

        assert calls[0].get("verifier_network_allowlist") is None
        agent_env.verifier_process_env.assert_not_called()
        exec_envs = [call.kwargs.get("env") for call in agent_env.exec.await_args_list]
        assert any(
            env is not None and env.get("HTTP_PROXY") == AGENT_PROXY_URL
            for env in exec_envs
        )
